var hierarchy =
[
    [ "IXICore.Utils._ByteArrayComparer", "class_i_x_i_core_1_1_utils_1_1___byte_array_comparer.html", null ],
    [ "IXICore.Meta.Activity", "class_i_x_i_core_1_1_meta_1_1_activity.html", null ],
    [ "IXICore.Meta.ActivityStorage", "class_i_x_i_core_1_1_meta_1_1_activity_storage.html", null ],
    [ "IXICore.Address", "class_i_x_i_core_1_1_address.html", null ],
    [ "IXICore.AddressClient", "class_i_x_i_core_1_1_address_client.html", null ],
    [ "IXICore.AddressData", "class_i_x_i_core_1_1_address_data.html", null ],
    [ "IXICore.AddressMatcher", "class_i_x_i_core_1_1_address_matcher.html", null ],
    [ "IXICore.CryptoKey.AsnKeyParser", "class_i_x_i_core_1_1_crypto_key_1_1_asn_key_parser.html", null ],
    [ "IXICore.CryptoKey.AsnParser", "class_i_x_i_core_1_1_crypto_key_1_1_asn_parser.html", null ],
    [ "IXICore.CryptoKey.BigInteger", "class_i_x_i_core_1_1_crypto_key_1_1_big_integer.html", null ],
    [ "IXICore.Utils.BitReader", "class_i_x_i_core_1_1_utils_1_1_bit_reader.html", null ],
    [ "IXICore.Utils.BitWriter", "class_i_x_i_core_1_1_utils_1_1_bit_writer.html", null ],
    [ "IXICore.Block", "class_i_x_i_core_1_1_block.html", null ],
    [ "IXICore.BlockHeader", "class_i_x_i_core_1_1_block_header.html", null ],
    [ "IXICore.Clock", "class_i_x_i_core_1_1_clock.html", null ],
    [ "IXICore.ConsensusConfig", "class_i_x_i_core_1_1_consensus_config.html", null ],
    [ "IXICore.Utils.ConsoleHelpers", "class_i_x_i_core_1_1_utils_1_1_console_helpers.html", null ],
    [ "IXICore.Core", "class_i_x_i_core_1_1_core.html", null ],
    [ "IXICore.CoreConfig", "class_i_x_i_core_1_1_core_config.html", null ],
    [ "IXICore.Network.CoreNetworkUtils", "class_i_x_i_core_1_1_network_1_1_core_network_utils.html", null ],
    [ "IXICore.CoreProtocolMessage", "class_i_x_i_core_1_1_core_protocol_message.html", null ],
    [ "IXICore.Crypto", "class_i_x_i_core_1_1_crypto.html", null ],
    [ "IXICore.CryptoLib", "class_i_x_i_core_1_1_crypto_lib.html", null ],
    [ "IXICore.CryptoManager", "class_i_x_i_core_1_1_crypto_manager.html", null ],
    [ "IXICore.GenericAPIServer", "class_i_x_i_core_1_1_generic_a_p_i_server.html", null ],
    [ "IComparer", null, [
      [ "IXICore.AddressComparer", "class_i_x_i_core_1_1_address_comparer.html", null ],
      [ "IXICore.Utils.ByteArrayComparer", "class_i_x_i_core_1_1_utils_1_1_byte_array_comparer.html", null ]
    ] ],
    [ "IXICore.ICryptoLib", "interface_i_x_i_core_1_1_i_crypto_lib.html", [
      [ "IXICore.BouncyCastle", "class_i_x_i_core_1_1_bouncy_castle.html", null ]
    ] ],
    [ "IEnumerator", null, [
      [ "IXICore.PresenceOrderedEnumerator", "class_i_x_i_core_1_1_presence_ordered_enumerator.html", null ]
    ] ],
    [ "IEqualityComparer", null, [
      [ "IXICore.Utils.ByteArrayComparer", "class_i_x_i_core_1_1_utils_1_1_byte_array_comparer.html", null ]
    ] ],
    [ "IXICore.Network.IPAndMask", "struct_i_x_i_core_1_1_network_1_1_i_p_and_mask.html", null ],
    [ "IXICore.Network.IPv4Subnet", "class_i_x_i_core_1_1_network_1_1_i_pv4_subnet.html", null ],
    [ "IXICore.Utils.IRandom", "interface_i_x_i_core_1_1_utils_1_1_i_random.html", [
      [ "IXICore.Utils.RNGCryptoServiceProviderRandom", "class_i_x_i_core_1_1_utils_1_1_r_n_g_crypto_service_provider_random.html", null ]
    ] ],
    [ "IXICore.Utils.IWordlistSource", "interface_i_x_i_core_1_1_utils_1_1_i_wordlist_source.html", [
      [ "IXICore.Utils.HardcodedWordlistSource", "class_i_x_i_core_1_1_utils_1_1_hardcoded_wordlist_source.html", null ]
    ] ],
    [ "IXICore.IxianKeyPair", "class_i_x_i_core_1_1_ixian_key_pair.html", null ],
    [ "IXICore.Meta.IxianNode", "class_i_x_i_core_1_1_meta_1_1_ixian_node.html", null ],
    [ "IXICore.IxiNumber", "class_i_x_i_core_1_1_ixi_number.html", null ],
    [ "IXICore.JsonError", "class_i_x_i_core_1_1_json_error.html", null ],
    [ "IXICore.JsonResponse", "class_i_x_i_core_1_1_json_response.html", null ],
    [ "IXICore.JsonRpcRequest", "class_i_x_i_core_1_1_json_rpc_request.html", null ],
    [ "IXICore.Utils.KDTable", "class_i_x_i_core_1_1_utils_1_1_k_d_table.html", null ],
    [ "IXICore.CryptoKey.KeyDerivation", "class_i_x_i_core_1_1_crypto_key_1_1_key_derivation.html", null ],
    [ "IXICore.Meta.Logging", "class_i_x_i_core_1_1_meta_1_1_logging.html", null ],
    [ "IXICore.Utils.Mnemonic", "class_i_x_i_core_1_1_utils_1_1_mnemonic.html", null ],
    [ "IXICore.Transaction.MultisigAddrAdd", "struct_i_x_i_core_1_1_transaction_1_1_multisig_addr_add.html", null ],
    [ "IXICore.Transaction.MultisigAddrDel", "struct_i_x_i_core_1_1_transaction_1_1_multisig_addr_del.html", null ],
    [ "IXICore.Transaction.MultisigChSig", "struct_i_x_i_core_1_1_transaction_1_1_multisig_ch_sig.html", null ],
    [ "IXICore.Transaction.MultisigTxData", "struct_i_x_i_core_1_1_transaction_1_1_multisig_tx_data.html", null ],
    [ "IXICore.Utils.NetDump", "class_i_x_i_core_1_1_utils_1_1_net_dump.html", null ],
    [ "IXICore.Network.NetOpsData", "struct_i_x_i_core_1_1_network_1_1_net_ops_data.html", null ],
    [ "IXICore.Utils.NetOutQueueItem", "struct_i_x_i_core_1_1_utils_1_1_net_out_queue_item.html", null ],
    [ "IXICore.Network.NetworkClientManager", "class_i_x_i_core_1_1_network_1_1_network_client_manager.html", null ],
    [ "IXICore.Network.NetworkEvents", "class_i_x_i_core_1_1_network_1_1_network_events.html", null ],
    [ "IXICore.Network.NetworkQueue", "class_i_x_i_core_1_1_network_1_1_network_queue.html", null ],
    [ "IXICore.Network.NetworkServer", "class_i_x_i_core_1_1_network_1_1_network_server.html", null ],
    [ "IXICore.Network.NetworkUtils", "class_i_x_i_core_1_1_network_1_1_network_utils.html", null ],
    [ "IXICore.Peer", "class_i_x_i_core_1_1_peer.html", null ],
    [ "IXICore.PeerStorage", "class_i_x_i_core_1_1_peer_storage.html", null ],
    [ "IXICore.PendingTransactions", "class_i_x_i_core_1_1_pending_transactions.html", null ],
    [ "IXICore.Platform", "class_i_x_i_core_1_1_platform.html", null ],
    [ "IXICore.Presence", "class_i_x_i_core_1_1_presence.html", null ],
    [ "IXICore.PresenceAddress", "class_i_x_i_core_1_1_presence_address.html", null ],
    [ "IXICore.PresenceList", "class_i_x_i_core_1_1_presence_list.html", null ],
    [ "IXICore.Network.QueueMessage", "struct_i_x_i_core_1_1_network_1_1_queue_message.html", null ],
    [ "IXICore.Network.QueueMessageRaw", "struct_i_x_i_core_1_1_network_1_1_queue_message_raw.html", null ],
    [ "IXICore.Utils.RandomUtils", "class_i_x_i_core_1_1_utils_1_1_random_utils.html", null ],
    [ "IXICore.Network.RemoteEndpoint", "class_i_x_i_core_1_1_network_1_1_remote_endpoint.html", [
      [ "IXICore.Network.NetworkClient", "class_i_x_i_core_1_1_network_1_1_network_client.html", null ]
    ] ],
    [ "IXICore.SuperBlockSegment", "class_i_x_i_core_1_1_super_block_segment.html", null ],
    [ "IXICore.Meta.ThreadLiveCheck", "class_i_x_i_core_1_1_meta_1_1_thread_live_check.html", null ],
    [ "IXICore.Network.TimeSyncData", "class_i_x_i_core_1_1_network_1_1_time_sync_data.html", null ],
    [ "IXICore.Transaction", "class_i_x_i_core_1_1_transaction.html", null ],
    [ "IXICore.TransactionInclusion", "class_i_x_i_core_1_1_transaction_inclusion.html", null ],
    [ "IXICore.UPnP", "class_i_x_i_core_1_1_u_pn_p.html", null ],
    [ "IXICore.Wallet", "class_i_x_i_core_1_1_wallet.html", null ],
    [ "IXICore.WalletState", "class_i_x_i_core_1_1_wallet_state.html", null ],
    [ "IXICore.WalletStorage", "class_i_x_i_core_1_1_wallet_storage.html", null ],
    [ "IXICore.Utils.Wordlist", "class_i_x_i_core_1_1_utils_1_1_wordlist.html", null ],
    [ "IXICore.WsChunk", "class_i_x_i_core_1_1_ws_chunk.html", null ]
];